# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BFS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftyJSON'
  pod 'Moya'
  pod 'SSZipArchive'
  pod 'RxSwift'

  # Pods for BFS

  target 'BFSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BFSUITests' do
    # Pods for testing
  end

end
